### ISSUE TITLE
Gradle and Maven actions don't work with current JDKs (LTS or newer)

### ISSUE THREAD

**Issue by michal-duda-sonarsource** [snyk/actions#11]
Maven and Gradle actions use images with JDK 8. The image that is used by those actions can't be overridden when using the action. This makes those actions unusable with Maven or Gradle projects that require higher JDKs for the build process (including Java 11 which is current LTS). 

It would be nice to be able to configure the image that is used by the action (for example `snyk/snyk:gradle-jdk11` instead of `snyk/snyk:gradle`) or to add missing actions to cover the images on https://github.com/snyk/snyk-images.

Using `setup-java` to install desired JDK before using Snyk Gradle action doesn't work- it results in an error described in issue https://github.com/snyk/actions/issues/6.

**Comment by derekoverby-baton** [comment]
I am observing this issue as well trying to execute snyk monitor using snyk/actions/maven@master after actions/setup-java@v1 configured for java 11.

**Comment by garethr** [comment]
Unfortunately it's not possible in GitHub Actions to configure the underlying image at the moment, I looked into this previously. The best approach is going to be to generate separate actions I think.

Let me generate 11 versions for Maven and Gradle now. If you could try those out and let me know if that works that would be appreciated. Then I'll generate the others as well.

**Comment by garethr** [comment]
If you could try out https://github.com/snyk/actions/tree/master/maven-3-jdk-11 and let me know if that solves your problem.

**Comment by derekoverby-baton** [comment]
It sure did! Thanks!
