### ISSUE TITLE
Resiliency request: Retry on "internal server error"

### ISSUE THREAD

**Issue by Maciek416** [snyk/actions#18]
We have encountered an error that suggests the snyk action can encounter network problems when talking to snyk's servers:

![image](https://user-images.githubusercontent.com/12995/87813332-8a19be00-c816-11ea-891b-f754b66f1b30.png)

Normally in the case of a workflow that was merely verifying a PR's contents before merge, we'd just retry the build. In the case of the above build, however, this is a workflow that runs after a PR is merged and verifies the team's integration branch, so there's not an opportunity to re-run the workflow before this sets off a cascade of notifications to various parties.

In cases like these, if snyk encounters an error that can be identified as a brief problem with snyk's servers and not the scan per se, would it be reasonable to have a retry (with exponential backoff) feature?

**Comment by garethr** [comment]
Thanks for the suggestion, and sorry for taking a while to get back to this. The Snyk Actions act as a minimal wrapper around the CLI, so I think functionality like this would belong there. This certainly feels useful for other integrations as well. Could I ask if you could open on https://github.com/snyk/snyk/issues if this is still an issue.
