### ISSUE TITLE
Docker: CLI option to disable suggestions for Dockerfile

### ISSUE THREAD

**Issue by stevenscg** [snyk/actions#3]
We use Packer to build our containers, so there are no Dockerfiles available to add to the `synk test` cli command.

Is there an option for the cli to disable suggestions other than the `synk config set ...` shown in the response below?? This is run in CI/CD.

```
Organization:      myorg
Package manager:   apk
Docker image:      myapp:${IMAGE_TAG}
Licenses:          enabled

Tested 43 dependencies for known issues, found 4 issues.

Pro tip: use `--file` option to get base image remediation advice.
Example: $ snyk test --docker myapp:${IMAGE_TAG} --file=path/to/Dockerfile

To remove this message in the future, please run `snyk config set disableSuggestions=true`

##[error]Docker run failed with exit code 1
```

**Comment by garethr** [comment]
Unfortunately the Snyk command doesn't have an option to do this today. I've just opened https://github.com/snyk/snyk/issues/880 to track.

Another approach is to drop a file into the home directory:

```
~/.config//configstore/snyk.json
{
        "disableSuggestions": "true"
}
```

It would be possible to modify the entrypoint script for images used here (
https://github.com/snyk/snyk-images/blob/master/docker-entrypoint.sh) to create the above file on provision of an ENV, if the upstream change to the CLI is going to take a while.

**Comment by garethr** [comment]
You can now specify an environment variable to disable this.

```
SNYK_CFG_DISABLESUGGESTIONS=true
```

**Comment by kasvtv** [comment]
For those still struggling with the above, neither of the two fixes listed above work anymore. You need to set `$DOCKER_SCAN_SUGGEST` to `"false"` now

**Comment by jurglic** [comment]
Hi @kasvtv 👋 
Can you share what version of `snyk` you are using? 
If you're using it with `docker scan`, no flag should be necessary as suggestions are muted by default.
